import { Button } from "@/components/shadcn-ui/button";
import {
  AlertTriangle,
  Info,
  ShieldCheck,
  Activity,
  BrainCircuit,
  FileWarning,
  Lock,
  CheckCircle,
  ArrowLeft,
} from "lucide-react";
import Link from "next/link";

export default function Disclaimer5XL() {
  return (
    <section
      className="mx-auto max-w-6xl px-6 py-28"
      aria-labelledby="disclaimer-heading"
    >
      {/* Header */}
      <div className="mb-6 flex items-center justify-between border-b py-6">
        <Button variant="ghost" size="sm" asChild className="group gap-2">
          <Link href="/">
            <ArrowLeft className="h-4 w-4 transition-transform group-hover:-translate-x-1" />
            Back To Home
          </Link>
        </Button>
      </div>

      <div className="max-w-5xl mx-auto">
        {/* Title */}
        <div className="mb-6 flex max-w-5xl items-center gap-3">
          <div className="rounded-lg bg-amber-500/10 p-2">
            <AlertTriangle className="h-6 w-6 text-amber-600 dark:text-amber-500" />
          </div>
          <h2
            id="disclaimer-heading"
            className="text-foreground text-2xl font-bold tracking-tight"
          >
            Comprehensive Medical Disclaimer
          </h2>
        </div>

        {/* Main Content Box */}
        <div className="bg-card/50 text-card-foreground border-border space-y-6 rounded-xl border p-6 shadow-sm sm:p-8">
          {/* Intro */}
          <p className="text-muted-foreground text-sm">
            This cardiovascular risk assessment tool uses AI-based algorithms to
            provide educational insights into heart health. Please read all
            sections carefully. Using this tool indicates your understanding and
            agreement with the terms outlined below.
          </p>

          {/* Emergency Banner */}
          <div className="bg-destructive/10 border-destructive/20 flex gap-4 rounded-lg border p-4">
            <Activity className="text-destructive mt-0.5 h-6 w-6 shrink-0" />
            <div>
              <h3 className="text-destructive text-sm font-semibold">
                Not for Emergencies
              </h3>
              <p className="text-destructive/80 mt-1 text-sm">
                If you experience chest pain, shortness of breath, fainting, or
                other severe symptoms,
                <strong> call emergency services immediately</strong>. Do not
                rely on this tool.
              </p>
            </div>
          </div>

          {/* Expanded List Points */}
          <ul className="space-y-4">
            <ListItem
              icon={<Info className="h-5 w-5 text-blue-500" />}
              title="Educational Use Only"
              text="This tool is for informational purposes only. It does not provide medical diagnoses and should not replace professional clinical judgment."
            />

            <ListItem
              icon={<BrainCircuit className="h-5 w-5 text-purple-500" />}
              title="AI Limitations & Reinforcement Learning Policy"
              text="Predictions are generated by an AI model trained on historical clinical data. A reinforcement learning-based policy is used to optimize scoring, but AI outputs are probabilistic and may be subject to errors or bias."
            />

            <ListItem
              icon={<ShieldCheck className="h-5 w-5 text-green-500" />}
              title="Data Privacy & Security"
              text="All user data is processed securely. We follow strict privacy standards and data protection protocols. Please review our Privacy Policy for details on handling and storage."
            />

            <ListItem
              icon={<Lock className="h-5 w-5 text-indigo-500" />}
              title="Prediction Confidence"
              text="While the AI model provides confidence metrics, individual health outcomes vary. The system’s confidence score does not guarantee clinical accuracy for any single user."
            />

            <ListItem
              icon={<CheckCircle className="h-5 w-5 text-green-400" />}
              title="Clinical Validation"
              text="The model has been trained and validated on large-scale datasets, but it is not a substitute for in-person medical evaluation."
            />

            <ListItem
              icon={<FileWarning className="h-5 w-5 text-orange-500" />}
              title="Scope & Boundaries"
              text="This tool is limited to certain cardiovascular risk indicators. It does not account for rare medical conditions or personalized factors outside the dataset."
            />

            <ListItem
              icon={<Activity className="h-5 w-5 text-red-500" />}
              title="Liability"
              text="The developers and affiliates provide this software 'as is' and are not liable for any decisions, clinical outcomes, or consequences resulting from use."
            />

            <ListItem
              icon={<Info className="h-5 w-5 text-blue-500" />}
              title="User Consent"
              text="By using this tool, you acknowledge that you understand these limitations and agree to proceed under your own discretion."
            />
          </ul>
        </div>
      </div>
    </section>
  );
}

// Helper component for list items
function ListItem({
  icon,
  title,
  text,
}: {
  icon: React.ReactNode;
  title: string;
  text: string;
}) {
  return (
    <li className="flex items-start gap-3">
      <span className="bg-background border-border mt-0.5 shrink-0 rounded-full border p-1.5 shadow-sm">
        {icon}
      </span>
      <div className="text-sm">
        <strong className="text-foreground mb-0.5 block font-semibold">
          {title}
        </strong>
        <span className="text-muted-foreground leading-relaxed">{text}</span>
      </div>
    </li>
  );
}
